#!/usr/bin/env php
<?php

use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Process\Exception\ProcessFailedException;
use Symfony\Component\Process\Process;

require __DIR__.'/bootstrap/autoload.php';

$app = require_once __DIR__.'/bootstrap/app.php';

$app->command('gethistory [--committer=] [--org=]', function (
    OutputInterface $output,
    \Alnutile\Codereview\GithubClientProvider $client,
    $committer, $org) use ($app) {

    $output->writeln("\nRunning your command\n");

    try {


        $query = [
            'committer' => $committer
        ];

        if($org) {
            $query['org'] = $org;
        }

        $results = $client->getLatestCommits($query);


        $table = new \Symfony\Component\Console\Helper\Table($output);
        $table
            ->setHeaders([
                'Date', 'Repo', 'CommitURL'
            ])->setRows($results);
        $table->render();


    } catch (\Exception $e) {
        $output->writeln(sprintf(
            "<error>Error</error>\n MESSAGE: %s\n",
            $e->getMessage()
        ));
    }

})->defaults([
    'org' => false
])
    ->descriptions("Show commit history of committer",
    [
        '--committer' => "Github Name"
    ]
);

$app->run();